# render.yaml
services:
  - type: web
    name: personal-management
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
    autoDeploy: true
